apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irene-p2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    # Route for vote-site
    - host: vote.irene-p2t.diogohack.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-service
                port:
                  number: 80

    # Route for result-site
    - host: result.irene-p2t.diogohack.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result-service
                port:
                  number: 80